http:
  addr: "127.0.0.1:9000"
internal:
  allows_on: false
  allows:
  blocks_on: false
  blocks:
    - "192.168.0.1"
external:
  allows_on: false
  blocks_on: false
# 5分钟
timeout: 300000000000
logger:
  type: 1   # 0:Console 1:RollingFile 2:DailyFile 3:DailyRollingFile
  level: 2  # 0:All 1:Trace 2:Debug 3:Info 4:Warn 5:Error 6:Fatal 7:Off
  file: "RabbitHome.log"
  max: 1048576 # 1MB
